# Datasource
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/votacao}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:dev123}

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Logs
logging.level.com.desafio=DEBUG
logging.level.org.springframework.web=DEBUG

# DevTools
spring.devtools.restart.enabled=true