# Datasource
spring.datasource.url=${DB_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# JPA
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate

# Logs
logging.level.com.desafio=INFO
logging.level.org.springframework.web=WARN

# DevTools desabilitado em prod
spring.devtools.restart.enabled=false